import { Course, Curriculum, Discussion, Notification, Progress, User, Assignment } from '../types';

export const currentUser: User = {
  id: 'user1',
  name: 'Sarah Johnson',
  email: 'sarah@example.com',
  role: 'student',
  avatar: 'https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=800',
};

export const notifications: Notification[] = [
  {
    id: 'notif1',
    title: 'New Message',
    message: 'You have a new message from your instructor',
    type: 'info',
    read: false,
    createdAt: '2025-05-10T14:48:00',
  },
  {
    id: 'notif2',
    title: 'Assignment Graded',
    message: 'Your UX Design Principles assignment has been graded',
    type: 'success',
    read: false,
    createdAt: '2025-05-09T09:23:00',
  },
  {
    id: 'notif3',
    title: 'Course Update',
    message: 'New materials added to React Fundamentals course',
    type: 'info',
    read: true,
    createdAt: '2025-05-08T16:30:00',
  },
  {
    id: 'notif4',
    title: 'Deadline Approaching',
    message: 'JavaScript Advanced Concepts assignment due in 2 days',
    type: 'warning',
    read: true,
    createdAt: '2025-05-07T10:15:00',
  },
];

export const courses: Course[] = [
  {
    id: 'course1',
    title: 'React Fundamentals',
    description: 'Learn the core concepts of React including components, props, state, and hooks with practical exercises and projects.',
    category: 'Web Development',
    level: 'beginner',
    instructor: {
      id: 'instructor1',
      name: 'David Chen',
      avatar: 'https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&w=800',
    },
    duration: '6 weeks',
    thumbnail: 'https://images.pexels.com/photos/11035471/pexels-photo-11035471.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    enrolledStudents: 1450,
    rating: 4.8,
    price: 79.99,
    tags: ['react', 'javascript', 'frontend'],
    updated: '2025-04-15T10:30:00',
  },
  {
    id: 'course2',
    title: 'UX Design Principles',
    description: 'Master the fundamentals of user experience design with emphasis on research, prototyping, and usability testing.',
    category: 'Design',
    level: 'intermediate',
    instructor: {
      id: 'instructor2',
      name: 'Maya Patel',
      avatar: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=800',
    },
    duration: '8 weeks',
    thumbnail: 'https://images.pexels.com/photos/3862130/pexels-photo-3862130.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    enrolledStudents: 2210,
    rating: 4.9,
    price: 89.99,
    tags: ['ux', 'design', 'prototyping'],
    updated: '2025-04-01T14:45:00',
  },
  {
    id: 'course3',
    title: 'Python for Data Science',
    description: 'Comprehensive introduction to Python programming for data analysis, visualization, and machine learning.',
    category: 'Data Science',
    level: 'beginner',
    instructor: {
      id: 'instructor3',
      name: 'James Wilson',
      avatar: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=800',
    },
    duration: '10 weeks',
    thumbnail: 'https://images.pexels.com/photos/7085/coffee-computer-writing-technology.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    enrolledStudents: 3180,
    rating: 4.7,
    price: 99.99,
    tags: ['python', 'data science', 'machine learning'],
    updated: '2025-03-20T09:15:00',
  },
  {
    id: 'course4',
    title: 'JavaScript Advanced Concepts',
    description: 'Deep dive into advanced JavaScript concepts including closures, prototypes, async programming, and modern ES6+ features.',
    category: 'Web Development',
    level: 'advanced',
    instructor: {
      id: 'instructor4',
      name: 'Alex Rodriguez',
      avatar: 'https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=800',
    },
    duration: '7 weeks',
    thumbnail: 'https://images.pexels.com/photos/270348/pexels-photo-270348.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    enrolledStudents: 1820,
    rating: 4.9,
    price: 129.99,
    tags: ['javascript', 'es6', 'async'],
    updated: '2025-04-05T16:20:00',
  },
  {
    id: 'course5',
    title: 'Mobile App Development with Flutter',
    description: 'Build cross-platform mobile applications using Flutter and Dart with hands-on projects for iOS and Android.',
    category: 'Mobile Development',
    level: 'intermediate',
    instructor: {
      id: 'instructor5',
      name: 'Nina Kim',
      avatar: 'https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=800',
    },
    duration: '9 weeks',
    thumbnail: 'https://images.pexels.com/photos/1092644/pexels-photo-1092644.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    enrolledStudents: 1560,
    rating: 4.6,
    price: 109.99,
    tags: ['flutter', 'dart', 'mobile'],
    updated: '2025-03-28T11:40:00',
  },
  {
    id: 'course6',
    title: 'Cloud Architecture on AWS',
    description: 'Learn to design, deploy, and manage applications on Amazon Web Services with focus on scalability and best practices.',
    category: 'Cloud Computing',
    level: 'advanced',
    instructor: {
      id: 'instructor6',
      name: 'Robert Johnson',
      avatar: 'https://images.pexels.com/photos/874158/pexels-photo-874158.jpeg?auto=compress&cs=tinysrgb&w=800',
    },
    duration: '11 weeks',
    thumbnail: 'https://images.pexels.com/photos/1181467/pexels-photo-1181467.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    enrolledStudents: 2090,
    rating: 4.8,
    price: 149.99,
    tags: ['aws', 'cloud', 'devops'],
    updated: '2025-04-10T08:55:00',
  },
];

export const enrolledCourses: string[] = ['course1', 'course2', 'course4'];

export const progress: Progress[] = [
  { courseId: 'course1', completed: 8, total: 24, lastAccessed: '2025-05-09T16:45:00' },
  { courseId: 'course2', completed: 12, total: 32, lastAccessed: '2025-05-10T09:30:00' },
  { courseId: 'course4', completed: 3, total: 28, lastAccessed: '2025-05-08T14:20:00' },
];

export const reactCurriculum: Curriculum = {
  courseId: 'course1',
  modules: [
    {
      id: 'module1',
      title: 'Introduction to React',
      description: 'Learn the basics of React and its core concepts',
      lessons: [
        {
          id: 'lesson1',
          title: 'What is React?',
          description: 'An overview of React and its place in modern web development',
          duration: '15 minutes',
          type: 'video',
          completed: true,
          videoUrl: 'https://example.com/videos/what-is-react',
        },
        {
          id: 'lesson2',
          title: 'Setting Up Your Development Environment',
          description: 'Installing and configuring the tools needed for React development',
          duration: '25 minutes',
          type: 'video',
          completed: true,
          videoUrl: 'https://example.com/videos/setup-environment',
        },
        {
          id: 'lesson3',
          title: 'Creating Your First React Component',
          description: 'Learning the basics of React components and JSX',
          duration: '30 minutes',
          type: 'video',
          completed: true,
          videoUrl: 'https://example.com/videos/first-component',
        },
        {
          id: 'lesson4',
          title: 'Introduction Quiz',
          description: 'Test your knowledge of React basics',
          duration: '15 minutes',
          type: 'quiz',
          completed: true,
        },
      ],
    },
    {
      id: 'module2',
      title: 'Working with Components and Props',
      description: 'Learn how to create reusable components and pass data between them',
      lessons: [
        {
          id: 'lesson5',
          title: 'Component Composition',
          description: 'Creating complex UIs by combining simple components',
          duration: '25 minutes',
          type: 'video',
          completed: true,
          videoUrl: 'https://example.com/videos/component-composition',
        },
        {
          id: 'lesson6',
          title: 'Props and Data Flow',
          description: 'Understanding how to pass data between components',
          duration: '30 minutes',
          type: 'video',
          completed: true,
          videoUrl: 'https://example.com/videos/props-data-flow',
        },
        {
          id: 'lesson7',
          title: 'PropTypes and Type Checking',
          description: 'Ensuring component reliability with prop validation',
          duration: '20 minutes',
          type: 'video',
          completed: true,
          videoUrl: 'https://example.com/videos/prop-types',
        },
        {
          id: 'lesson8',
          title: 'Component Building Exercise',
          description: 'Practice creating and composing components',
          duration: '45 minutes',
          type: 'assignment',
          completed: true,
        },
      ],
    },
    {
      id: 'module3',
      title: 'State Management and Hooks',
      description: 'Learn how to manage state in React applications',
      lessons: [
        {
          id: 'lesson9',
          title: 'Introduction to State',
          description: 'Understanding component state and when to use it',
          duration: '20 minutes',
          type: 'video',
          completed: true,
          videoUrl: 'https://example.com/videos/intro-state',
        },
        {
          id: 'lesson10',
          title: 'React Hooks Overview',
          description: 'Introduction to the hooks API and its benefits',
          duration: '25 minutes',
          type: 'video',
          completed: false,
          videoUrl: 'https://example.com/videos/hooks-overview',
        },
        {
          id: 'lesson11',
          title: 'useState Hook',
          description: 'Managing component state with the useState hook',
          duration: '30 minutes',
          type: 'video',
          completed: false,
          videoUrl: 'https://example.com/videos/use-state',
        },
        {
          id: 'lesson12',
          title: 'useEffect Hook',
          description: 'Handling side effects in functional components',
          duration: '35 minutes',
          type: 'video',
          completed: false,
          videoUrl: 'https://example.com/videos/use-effect',
        },
        {
          id: 'lesson13',
          title: 'State Management Exercise',
          description: 'Build a small application using hooks',
          duration: '60 minutes',
          type: 'assignment',
          completed: false,
        },
      ],
    },
    {
      id: 'module4',
      title: 'Routing and Navigation',
      description: 'Creating multi-page applications with React Router',
      lessons: [
        {
          id: 'lesson14',
          title: 'Introduction to React Router',
          description: 'Understanding client-side routing in React applications',
          duration: '25 minutes',
          type: 'video',
          completed: false,
          videoUrl: 'https://example.com/videos/intro-router',
        },
        {
          id: 'lesson15',
          title: 'Setting Up Routes',
          description: 'Configuring routes and navigation in your application',
          duration: '30 minutes',
          type: 'video',
          completed: false,
          videoUrl: 'https://example.com/videos/setup-routes',
        },
        {
          id: 'lesson16',
          title: 'Navigation and Route Parameters',
          description: 'Working with dynamic routes and navigation',
          duration: '35 minutes',
          type: 'video',
          completed: false,
          videoUrl: 'https://example.com/videos/route-params',
        },
        {
          id: 'lesson17',
          title: 'Protected Routes and Authentication',
          description: 'Implementing authentication and protected routes',
          duration: '40 minutes',
          type: 'video',
          completed: false,
          videoUrl: 'https://example.com/videos/protected-routes',
        },
        {
          id: 'lesson18',
          title: 'Routing Project',
          description: 'Build a multi-page application with React Router',
          duration: '90 minutes',
          type: 'assignment',
          completed: false,
        },
      ],
    },
  ],
};

export const discussions: Discussion[] = [
  {
    id: 'disc1',
    courseId: 'course1',
    userId: 'user2',
    userName: 'Emily Thompson',
    userAvatar: 'https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=800',
    message: 'I\'m having trouble understanding how to properly use the useEffect hook. Can someone explain the dependency array?',
    createdAt: '2025-05-09T11:24:00',
    replies: [
      {
        id: 'reply1',
        userId: 'instructor1',
        userName: 'David Chen',
        userAvatar: 'https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&w=800',
        message: 'The dependency array tells React which values from the component scope the effect depends on. If those values change, the effect will re-run. If you provide an empty array, the effect only runs once after the initial render.',
        createdAt: '2025-05-09T12:45:00',
        likes: 5,
      },
      {
        id: 'reply2',
        userId: 'user3',
        userName: 'Michael Brown',
        userAvatar: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=800',
        message: 'I found this article really helpful for understanding useEffect: https://example.com/react-hooks-guide',
        createdAt: '2025-05-09T14:18:00',
        likes: 3,
      },
    ],
    likes: 8,
  },
  {
    id: 'disc2',
    courseId: 'course1',
    userId: 'user4',
    userName: 'Jessica Lee',
    userAvatar: 'https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=800',
    message: 'Has anyone completed the final project yet? I\'m looking for some inspiration on how to structure my component hierarchy.',
    createdAt: '2025-05-10T09:32:00',
    replies: [
      {
        id: 'reply3',
        userId: 'user5',
        userName: 'Daniel Martinez',
        userAvatar: 'https://images.pexels.com/photos/837358/pexels-photo-837358.jpeg?auto=compress&cs=tinysrgb&w=800',
        message: 'I finished it last week. I found it helpful to sketch out the component tree before coding. I started with container components for each major feature and then broke those down into smaller presentation components.',
        createdAt: '2025-05-10T10:15:00',
        likes: 6,
      },
    ],
    likes: 4,
  },
];

export const assignments: Assignment[] = [
  {
    id: 'assign1',
    courseId: 'course1',
    title: 'Building a Todo App with React Hooks',
    description: 'Create a simple todo application using React hooks for state management. The app should allow users to add, delete, and mark todos as complete.',
    dueDate: '2025-05-15T23:59:59',
    status: 'in_progress',
  },
  {
    id: 'assign2',
    courseId: 'course2',
    title: 'UX Research Report',
    description: 'Conduct a usability study on a website of your choice and write a detailed report on your findings, including recommendations for improvements.',
    dueDate: '2025-05-12T23:59:59',
    status: 'submitted',
  },
  {
    id: 'assign3',
    courseId: 'course4',
    title: 'Advanced JavaScript Patterns Implementation',
    description: 'Implement three design patterns (Observer, Factory, and Module) in JavaScript and write tests for each implementation.',
    dueDate: '2025-05-20T23:59:59',
    status: 'not_started',
  },
  {
    id: 'assign4',
    courseId: 'course2',
    title: 'Prototype Design for Mobile App',
    description: 'Create a high-fidelity prototype for a mobile application following the design principles covered in the course.',
    dueDate: '2025-05-05T23:59:59',
    status: 'graded',
    grade: 92,
    feedback: 'Excellent work on the information architecture and user flow. The visual hierarchy is clear and consistent. Consider adding more contrast for accessibility in future designs.',
  },
];